[tools]
# core
"act" = "latest"
"age" = "latest"
"air" = "latest"
"ansible-core" = "latest"
"argo" = "latest"
"argocd" = "latest"
"ast-grep" = "latest"
"aws-iam-authenticator" = "latest"
"azure-cli" = "latest"
"buf" = "latest"
"bun" = "latest"
"caddy" = "latest"
"cfssl" = "latest"
"cheat" = "latest"
"cloudflared" = "latest"
"cockroach" = "latest"
"curlie" = "latest"
"dasel" = "latest"
"dotnet" = "latest"
"duckdb" = "latest"
"dust" = "latest"
"dyff" = "latest"
"eksctl" = "latest"
"fd" = "latest"
"ffmpeg" = "latest"
"fx" = "latest"
"gh" = "latest"
"go" = "latest"
"golangci-lint" = "latest"
"grpcurl" = "latest"
"gum" = "latest"
"helm" = "4"
"hexyl" = "latest"
"hyperfine" = "latest"
"istioctl" = "latest"
"jless" = "latest"
"jq" = "latest"
"just" = "latest"
"k9s" = "latest"
"kn" = "latest"
"krew" = "latest"
"kube-linter" = "latest"
"kubeconform" = "latest"
"kubectl" = "latest"
"kubectx" = "latest"
"kubeshark" = "latest"
"kubie" = "latest"
"kustomize" = "latest"
"lazydocker" = "latest"
"lazygit" = "latest"
"node" = "latest"
"opentofu" = "latest"
"peco" = "latest"
"pipx" = "latest"
"pre-commit" = "latest"
"protobuf" = "latest"
"python" = "latest"
"ripgrep" = "latest"
"rtk" = "latest"
"ruby" = "latest"
"ruff" = "latest"
"rust" = "latest"
"sd" = "latest"
"skaffold" = "latest"
"sqlite" = "latest"
"steampipe" = "latest"
"stern" = "latest"
"terraform" = "latest"
"terragrunt" = "latest"
"terramate" = "latest"
"tfmigrate" = "latest"
"uv" = "latest"
"vault" = "latest"
"xh" = "latest"
"yq" = "latest"
# aqua
"aqua:yarnpkg/berry" = "latest"
# github
"github:ByteNess/aws-vault" = "latest"
"github:cilium/cilium-cli" = "latest"
"github:crabbuild/compass" = "latest"
"github:ctxrs/ctx" = "latest"
"github:datadog-labs/pup" = "latest"
"github:googleworkspace/cli" = "latest"
"github:grafana/k6" = "latest"
"github:helmfile/helmfile" = "latest"
"github:jgm/pandoc" = "latest"
"github:lingrino/vaku" = "latest"
"github:microsoft/tgrep" = "latest"
"github:openbao/openbao" = "latest"
"github:sharkdp/bat" = "latest"
"github:siderolabs/talos" = "latest"
"github:str4d/age-plugin-yubikey" = "latest"
"github:theryangeary/choose" = "latest"
"github:wezm/git-grab" = "latest"
"github:zellij-org/zellij" = "latest"
# npm
"npm:@toon-format/cli" = "latest"
"npm:ccusage" = "latest"
"npm:next" = "latest"
# pipx
"pipx:claude-swap" = "latest"
"pipx:datasette" = "latest"
"pipx:headroom-ai[all]" = "latest"
"pipx:httpie" = "latest"
"pipx:llm" = "latest"
"pipx:mypy" = "latest"
"pipx:pyp" = "latest"
"pipx:pyright" = "latest"
"pipx:pz" = "latest"
"pipx:reloader.py" = "latest"
"pipx:virtualenv" = "latest"
"pipx:visidata" = "latest"
