# ghostty.conf for herdr
title = herdr
quit-after-last-window-closed = true
window-save-state = never
shell-integration = none
env = SHLVL=0

# ghostty
keybind = super+.=toggle_command_palette
keybind = super+shift+.=reload_config

# workspaces
keybind = ctrl+shift+up=unbind
keybind = ctrl+shift+down=unbind
keybind = super+n=unbind
keybind = super+alt+w=unbind
keybind = super+shift+r=unbind

# tabs
keybind = ctrl+left=unbind
keybind = ctrl+right=unbind
keybind = super+digit_1=unbind
keybind = super+digit_2=unbind
keybind = super+digit_3=unbind
keybind = super+digit_4=unbind
keybind = super+digit_5=unbind
keybind = super+digit_6=unbind
keybind = super+digit_7=unbind
keybind = super+digit_8=unbind
keybind = super+digit_9=unbind
keybind = super+1=unbind
keybind = super+2=unbind
keybind = super+3=unbind
keybind = super+4=unbind
keybind = super+5=unbind
keybind = super+6=unbind
keybind = super+7=unbind
keybind = super+8=unbind
keybind = super+9=unbind
keybind = super+r=unbind
keybind = super+t=unbind
keybind = super+w=unbind
keybind = super+shift+w=unbind

# splits & panes
keybind = ctrl+alt+left=unbind
keybind = ctrl+alt+right=unbind
keybind = ctrl+alt+up=unbind
keybind = ctrl+alt+down=unbind
keybind = ctrl+alt+enter=unbind
keybind = ctrl+home=text:\x02v
keybind = ctrl+end=text:\x02v
keybind = ctrl+page_up=text:\x02-
keybind = ctrl+page_down=text:\x02-
keybind = ctrl+enter=unbind
keybind = super+d=unbind
keybind = super+alt+r=unbind
keybind = super+shift+d=unbind
keybind = super+left_bracket=text:\x02\x1b[Z
keybind = super+right_bracket=text:\x02\x09

# agents
keybind = ctrl+up=unbind
keybind = ctrl+down=unbind

# sidebar & session
keybind = super+b=unbind
keybind = super+e=unbind
keybind = super+g=unbind
keybind = super+j=unbind
keybind = super+k=unbind
keybind = super+o=unbind
keybind = super+p=unbind
keybind = super+shift+p=unbind
keybind = super+,=unbind
keybind = super+shift+,=unbind
keybind = super+comma=unbind
keybind = super+shift+comma=unbind
keybind = super+shift+slash=text:\x02?
